# Generated by Django 5.1.7 on 2025-06-01 18:35

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('rub', 'Рубли'), ('usd', 'Доллары')], default='usd', max_length=3),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена не может быть отрицательной или равной нулю', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.5'))]),
        ),
    ]
